export const healthScenes = [
  { id: "bills", name: "Las facturas", nameEn: "Medical bills", title: "La atención médica puede implicar gastos imprevistos.", titleEn: "Medical care can bring unexpected costs.", text: "Los gastos de una atención médica pueden afectar tu presupuesto.", textEn: "Medical expenses can affect your household budget.", x: 29, y: 76, path: "M0 557 L672 681 Q710 712 669 748 Q494 864 0 941Z" },
  { id: "loans", name: "Los préstamos", nameEn: "Borrowing money", title: "Un gasto inesperado puede cambiar tus planes.", titleEn: "An unexpected expense can change your plans.", text: "Los gastos inesperados pueden afectar más que tu presupuesto mensual.", textEn: "Unexpected costs can affect more than your monthly budget.", x: 29, y: 55, path: "M0 380 L796 503 Q807 520 821 605 Q825 650 688 711 L0 556Z" },
  { id: "help", name: "Pedir ayuda", nameEn: "Asking for help", title: "El apoyo comunitario es una opción, no un plan financiero.", titleEn: "Community support is an option, not a financial plan.", text: "Cada familia puede encontrar apoyo de distintas maneras. Explora opciones antes de decidir.", textEn: "Families find support in different ways. Explore options before deciding.", x: 28, y: 35, path: "M0 174 L762 320 L799 503 L0 379Z" },
  { id: "uncertainty", name: "La incertidumbre", nameEn: "Uncertainty", title: "Entender tus opciones forma parte de tu preparación.", titleEn: "Understanding your options is part of preparing.", text: "Los gastos y beneficios varían según la situación y la póliza. Entenderlos puede ayudarte a prepararte.", textEn: "Costs and benefits vary with the situation and the policy. Understanding them may help you prepare.", x: 29, y: 17, path: "M0 0 L692 121 Q715 125 720 150 L763 321 L0 172Z" },
  { id: "medical", name: "Tu seguro médico", nameEn: "Your health insurance", title: "Conocer los detalles de tu cobertura importa.", titleEn: "Understanding your coverage details matters.", text: "Revisamos tu red médica, medicamentos, deducible y gastos de bolsillo.", textEn: "We review your provider network, prescriptions, deductible, and out-of-pocket costs.", x: 76, y: 78, path: "M1009 683 L1671 611 L1671 941 L1360 941 Q1090 850 1000 748 Q983 713 1009 683Z" },
  { id: "benefits", name: "Un respaldo extra", nameEn: "Extra support", title: "Considera si los beneficios adicionales encajan contigo.", titleEn: "Consider whether additional benefits fit your needs.", text: "Algunas pólizas ofrecen beneficios por eventos cubiertos. Los términos y beneficios varían según la póliza.", textEn: "Some policies offer benefits for covered events. Terms and benefits vary by policy.", x: 75, y: 57, path: "M905 510 L1671 412 L1671 610 L1009 682 Q900 655 895 608Z" },
  { id: "dental", name: "Dental y visión", nameEn: "Dental and vision", title: "También puedes comparar dental y visión.", titleEn: "You can also compare dental and vision.", text: "Revisamos redes, límites, costos y períodos de espera de las opciones disponibles.", textEn: "We review networks, limits, costs, and waiting periods for available options.", x: 76, y: 36, path: "M975 311 L1671 191 L1671 411 L905 509 L941 343 Q944 323 975 311Z" },
  { id: "family", name: "Tu familia", nameEn: "Your family", title: "Entender tus opciones te ayuda a decidir.", titleEn: "Understand your options to make an informed choice.", text: "Una decisión informada comienza por entender qué tienes y qué opciones están disponibles.", textEn: "An informed choice starts with understanding what you have and what options are available.", x: 76, y: 17, path: "M1515 0 L1671 0 L1671 189 L975 310 L1019 141 Q1023 122 1040 116Z" },
] as const;
