export const healthScenes = [
  { id: "bills", name: "Las facturas", nameEn: "Medical bills", title: "La salud no debería convertirse en una deuda.", titleEn: "Your health should not become debt.", text: "Sin cobertura, los gastos médicos pueden recaer directamente en tu familia.", textEn: "Without coverage, medical expenses may fall directly on your family.", x: 29, y: 76, path: "M0 557 L672 681 Q710 712 669 748 Q494 864 0 941Z" },
  { id: "loans", name: "Los préstamos", nameEn: "Borrowing money", title: "Una emergencia no debería decidir tus finanzas.", titleEn: "An emergency should not decide your finances.", text: "Una emergencia puede comprometer mucho más que tus ahorros.", textEn: "An emergency can put much more than your savings at risk.", x: 29, y: 55, path: "M0 380 L796 503 Q807 520 821 605 Q825 650 688 711 L0 556Z" },
  { id: "help", name: "Pedir ayuda", nameEn: "Asking for help", title: "Tu recuperación no debería depender de una colecta.", titleEn: "Your recovery should not depend on a fundraiser.", text: "Depender de una colecta añade incertidumbre en un momento difícil.", textEn: "Relying on a fundraiser adds uncertainty during a difficult moment.", x: 28, y: 35, path: "M0 174 L762 320 L799 503 L0 379Z" },
  { id: "uncertainty", name: "La incertidumbre", nameEn: "Uncertainty", title: "Proteger tu salud también es proteger lo que has construido.", titleEn: "Protecting your health also protects what you have built.", text: "Estos son escenarios posibles, no destinos inevitables. Hay otra forma de prepararte.", textEn: "These are possible scenarios, not inevitable outcomes. There is another way to prepare.", x: 29, y: 17, path: "M0 0 L692 121 Q715 125 720 150 L763 321 L0 172Z" },
  { id: "medical", name: "Tu seguro médico", nameEn: "Your health insurance", title: "Saber que puedes atenderte cambia todo.", titleEn: "Knowing you can get care changes everything.", text: "Revisamos tu red médica, medicamentos, deducible y gastos de bolsillo.", textEn: "We review your provider network, prescriptions, deductible, and out-of-pocket costs.", x: 76, y: 78, path: "M1009 683 L1671 611 L1671 941 L1360 941 Q1090 850 1000 748 Q983 713 1009 683Z" },
  { id: "benefits", name: "Un respaldo extra", nameEn: "Extra support", title: "La vida sigue. Tu respaldo también importa.", titleEn: "Life continues. Your support still matters.", text: "Explora beneficios complementarios ante accidentes, cáncer, derrame cerebral y hospitalización.", textEn: "Explore supplemental benefits for covered accidents, cancer, stroke, and hospitalization.", x: 75, y: 57, path: "M905 510 L1671 412 L1671 610 L1009 682 Q900 655 895 608Z" },
  { id: "dental", name: "Dental y visión", nameEn: "Dental and vision", title: "Ver, sonreír y sentirte bien también importa.", titleEn: "Seeing, smiling, and feeling well matter too.", text: "Comparamos opciones de dental y visión: redes, límites y períodos de espera.", textEn: "We compare dental and vision options, including networks, limits, and waiting periods.", x: 76, y: 36, path: "M975 311 L1671 191 L1671 411 L905 509 L941 343 Q944 323 975 311Z" },
  { id: "family", name: "Tu familia", nameEn: "Your family", title: "Más claridad. Más momentos juntos.", titleEn: "More clarity. More moments together.", text: "La tranquilidad empieza por saber qué tienes, qué falta y qué tiene sentido para ti.", textEn: "Peace of mind begins with knowing what you have, what is missing, and what makes sense for you.", x: 76, y: 17, path: "M1515 0 L1671 0 L1671 189 L975 310 L1019 141 Q1023 122 1040 116Z" },
] as const;
